[package]
name = "rust_wfchat_recog"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-glyph-recog = { git = "https://github.com/davidneumann/rust-glyph-recog" }
